[package]
name = "turbo-incremental"
version = "0.1.0"
edition = "2024"

[dependencies]
turbo = { version = "3.0.0-alpha.4", package = "turbo-genesis-sdk" }
once_cell = "1.17"

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(no_run)'] }
