[package]
name = "turbo-incremental"
version = "0.1.0"
edition = "2024"

[dependencies]
turbo = { version = "2.0.0-alpha.10", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(no_run)'] }
