use super::*;
use once_cell::sync::Lazy;

pub static EXOPLANET_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "FIELD SCANNER".to_string(),
        description: "Increase the amount of research gathered by pressing the Exoplanet by 1".to_string(),
        cost: vec![(Resources::Research, 15)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 4,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Research, 15)],
    },
    Upgrade {
        name: "DEPLOY SURVEY DRONE".to_string(),
        description: "Assign a DRONE to gather RESEARCH".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![2],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "ADV. SENSORS".to_string(),
        description: "Increase the amount of RESEARCH gathered by SURVEY DRONES by 16".to_string(),
        cost: vec![(Resources::Metals, 32)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 32)],
    },
    Upgrade {
        name: "BIOSCANNERS".to_string(),
        description: "Increase the speed of SURVEY DRONES by 10%".to_string(),
        cost: vec![(Resources::Power, 40)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 40)],
    },
]);

pub static DEPOT_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct DRONE DEPOT.".to_string(),
        cost: vec![(Resources::Research, 60)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 60)],
    },
    Upgrade {
        name: "DRONE SHIPMENT".to_string(),
        description: "Exchange RESEARCH for a DRONE".to_string(),
        cost: vec![(Resources::Research, 120)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        buy_button: Btn::buy(),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::Exponential,
        base_cost: vec![(Resources::Research, 120)],
    },
    Upgrade {
        name: "CONSTRUCT FABRICATOR".to_string(),
        description: "Construct FABRICATOR. Assign DRONES to convert METAL into DRONES".to_string(),
        cost: vec![(Resources::Research, 4800), (Resources::Metals, 2400)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 3800), (Resources::Metals, 1200)],
    },    
    Upgrade {
        name: "DEPLOY MAKER DRONE".to_string(),
        description: "Assign a DRONE to fabricate DRONES".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "CARGO CAPACITY".to_string(),
        description: "Increase the amount of METALS gathered by MAKER DRONES by 24".to_string(),
        cost: vec![(Resources::Metals, 860)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 30,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 860)],
    },
    Upgrade {
        name: "PLASMA TOOLS".to_string(),
        description: "Increase the speed of MAKER DRONES by 20%".to_string(),
        cost: vec![(Resources::Power,240)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 30,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 240)],
    },
]);

pub static MINES_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct ASTEROID MINES".to_string(),
        cost: vec![(Resources::Research, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1, 2],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 800)],
    },
    Upgrade {
        name: "DEPLOY MINING DRONE".to_string(),
        description: "Assign a DRONE to gather METALS".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "DRILL AUGMENT".to_string(),
        description: "Increase the amount of METALS gathered by MINING DRONES by 18".to_string(),
        cost: vec![(Resources::Metals, 120)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 20,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 120)],
    },
    Upgrade {
        name: "ADV. THRUSTERS".to_string(),
        description: "Increase the speed of MINING DRONES by 10%".to_string(),
        cost: vec![(Resources::Power, 100)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 20,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 100)],
    },
]);

pub static POWER_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct POWER PLANT".to_string(),
        cost: vec![(Resources::Research, 3200), (Resources::Metals, 1200)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1,2,3],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 3200), (Resources::Metals, 1200)],
    },
    Upgrade {
        name: "DEPLOY CONDUIT DRONE".to_string(),
        description: "Assign a DRONE to gather POWER".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "REFLECTOR CELLS".to_string(),
        description: "Increase the amount of POWER gathered by CONDUIT DRONES by 12".to_string(),
        cost: vec![(Resources::Metals, 220)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 220)],
    },
    Upgrade {
        name: "ARC BATTERIES".to_string(),
        description: "Increase the speed of CONDUIT DRONES by 10%".to_string(),
        cost: vec![(Resources::Power, 350)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 350)],
    },
]);

pub static GATE_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct JUMP GATE".to_string(),
        cost: vec![(Resources::Research, 160_000), (Resources::Metals, 80_000), (Resources::Power, 40_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 240_000), (Resources::Metals, 90_000), (Resources::Power, 50_000)],
    },
    Upgrade {
        name: "JUMP TO NEXT SECTOR".to_string(),
        description: "End game. Proceed to next sector and start again".to_string(),
        cost: vec![], //vec![(Resources::Research, 240_000), (Resources::Metals, 90_000), (Resources::Power, 50_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![], //vec![(Resources::Research, 240_000), (Resources::Metals, 120_000), (Resources::Power, 80_000)],
    },
]);

pub static COMPLEX_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct RESEARCH COMPLEX".to_string(),
        cost: vec![(Resources::Research, 6400), (Resources::Metals, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 0)],
    },
    Upgrade {
        name: "DEPLOY RESEARCH DRONE".to_string(),
        description: "Assign a DRONE to complete RESEARCH PROJECTS".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
]);