use super::*;
use once_cell::sync::Lazy;

pub static UNASSIGN: Lazy<Upgrade> = Lazy::new(|| Upgrade {
    name: "UNASSIGN".to_string(),
    description: "Unassign a DRONE from this station".to_string(),
    cost: vec![],
    entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
    level: 0,
    max_level: u32::MAX,
    unlocks: vec![],
    u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },
    tooltip: WrapBox::new("".to_string(), 0),
    hovered: false,
    display_lvl: false,
    cost_formula: CostFormula::None,
    base_cost: vec![],
});

pub static EXOPLANET_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "FIELD SCANNER".to_string(),
        description: "Increase RESEARCH gathered by clicking EXOPLANET by 1".to_string(),
        cost: vec![],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 4,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Research, 15)],
    },
    Upgrade {
        name: "DEPLOY SURVEY DRONE".to_string(),
        description: "Assign a DRONE to gather RESEARCH".to_string(),
        cost: vec![], // vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1_000_000_000,
        unlocks: vec![2],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "ADV. SENSORS".to_string(),
        description: "Increase the EFFICENCY of SURVEY DRONES by 85%".to_string(),
        cost: vec![], // vec![(Resources::Metals, 32)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Metals, 32)],
    },
    Upgrade {
        name: "BIOSCANNERS".to_string(),
        description: "Increase the SPEED of SURVEY DRONES by 5%".to_string(),
        cost: vec![], // vec![(Resources::Power, 40)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Power, 200)],
    },
    Upgrade {
        name: "DATA COMPRESSION".to_string(),
        description: "Increase the BASE of SURVEY DRONES by 3".to_string(),
        cost: vec![], // vec![(Resources::Power, 40)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Research, 740)],
    },
]);

pub static DEPOT_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct DRONE DEPOT".to_string(),
        cost: vec![], // vec![(Resources::Research, 60)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 60)],
    },
    Upgrade {
        name: "DRONE SHIPMENT".to_string(),
        description: "Exchange RESEARCH for a DRONE".to_string(),
        cost: vec![], // vec![(Resources::Research, 120)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        level: 0,
        max_level: 20_000,
        unlocks: vec![],
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::Exponential {factor: 1.1},
        base_cost: vec![(Resources::Research, 120)],
    },
    Upgrade {
        name: "CONSTRUCT FABRICATOR".to_string(),
        description: "Construct FABRICATOR. Assign DRONES to convert METAL into DRONES".to_string(),
        cost: vec![], // vec![(Resources::Research, 4800), (Resources::Metals, 2400)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![7],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 320_000), (Resources::Metals, 180_000)],
    },    
    Upgrade {
        name: "DEPLOY MAKER DRONE".to_string(),
        description: "Assign a DRONE to fabricate DRONES".to_string(),
        cost: vec![], // vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1_000_000_000,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "CARGO CAPACITY".to_string(),
        description: "Increase the EFFICENCY of MAKER DRONES by 90%".to_string(),
        cost: vec![], // vec![(Resources::Metals, 860)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Metals, 16_640)],
    },
    Upgrade {
        name: "PLASMA TOOLS".to_string(),
        description: "Increase the SPEED of MAKER DRONES by 4%".to_string(),
        cost: vec![], // vec![(Resources::Power,240)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Power, 8_240)],
    },
    Upgrade {
        name: "ADV. SCHEMATICS".to_string(),
        description: "Increase the BASE of MAKER DRONES by 5".to_string(),
        cost: vec![], // vec![(Resources::Power,240)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Research, 24_860)],
    },
    Upgrade {
        name: "DISABLE FABRICATOR".to_string(),
        description: "Toggle the FABRICATOR operating".to_string(),
        cost: vec![], // vec![(Resources::Research, 900)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), true) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![],
    },
]);

pub static MINES_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct ASTEROID MINES".to_string(),
        cost: vec![], // vec![(Resources::Research, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1, 2],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 800)],
    },
    Upgrade {
        name: "DEPLOY MINING DRONE".to_string(),
        description: "Assign a DRONE to gather METALS".to_string(),
        cost: vec![], // vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1_000_000_000,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "DRILL AUGMENT".to_string(),
        description: "Increase the EFFICENCY of MINING DRONES by 90%".to_string(),
        cost: vec![], // vec![(Resources::Metals, 120)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Metals, 120)],
    },
    Upgrade {
        name: "ADV. THRUSTERS".to_string(),
        description: "Increase the SPEED of MINING DRONES by 8%".to_string(),
        cost: vec![], // vec![(Resources::Power, 100)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },   

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Power, 90)],
    },
    Upgrade {
        name: "ORE CONDENSER".to_string(),
        description: "Increase the BASE of MINING DRONES by 5".to_string(),
        cost: vec![], // vec![(Resources::Power, 40)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 99,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Research, 920)],
    },
]);

pub static POWER_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct POWER PLANT".to_string(),
        cost: vec![], // vec![(Resources::Research, 3200), (Resources::Metals, 1200)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1,2,3],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },   

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 3200), (Resources::Metals, 1200)],
    },
    Upgrade {
        name: "DEPLOY CONDUIT DRONE".to_string(),
        description: "Assign a DRONE to gather POWER".to_string(),
        cost: vec![], // vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1_000_000_000,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "REFLECTOR CELLS".to_string(),
        description: "Increase the EFFICENCY of CONDUIT DRONES by 85%".to_string(),
        cost: vec![], // vec![(Resources::Metals, 220)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },
        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Metals, 220)],
    },
    Upgrade {
        name: "ARC BATTERIES".to_string(),
        description: "Increase the SPEED of CONDUIT DRONES by 6%".to_string(),
        cost: vec![], // vec![(Resources::Power, 350)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Power, 120)],
    },
    Upgrade {
        name: "POWER AMPS".to_string(),
        description: "Increase the BASE of CONDUIT DRONES by 4".to_string(),
        cost: vec![], // vec![(Resources::Power, 350)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Research, 1_080)],
    },
]);

pub static GATE_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct JUMP GATE".to_string(),
        cost: vec![], // vec![(Resources::Research, 160_000), (Resources::Metals, 80_000), (Resources::Power, 40_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 50_000), (Resources::Metals, 24_000), (Resources::Power, 15_000)],
    },
    Upgrade {
        name: "JUMP TO NEXT SECTOR".to_string(),
        description: "Earn Prestige. Proceed to next sector and start again".to_string(),
        cost: vec![], // vec![], //vec![(Resources::Research, 240_000), (Resources::Metals, 90_000), (Resources::Power, 50_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 10000000,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![], //vec![(Resources::Research, 240_000), (Resources::Metals, 120_000), (Resources::Power, 80_000)],
    },
]);

pub static COMPLEX_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct RESEARCH COMPLEX".to_string(),
        cost: vec![], // vec![(Resources::Research, 6400), (Resources::Metals, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![5, 6, 7],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 120_000), (Resources::Metals, 68_000), (Resources::Power, 32_000)],
    },
    Upgrade {
        name: "DEPLOY RESEARCH DRONE".to_string(),
        description: "Assign a DRONE to complete RESEARCH PROJECTS".to_string(),
        cost: vec![], // vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1_000_000_000,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "ADV. DATABASE".to_string(),
        description: "Increase the BASE of RESEARCH DRONES by 4".to_string(),
        cost: vec![], // vec![(Resources::Research, 12_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Research, 4_080)],
    },
    Upgrade {
        name: "MACHINE LEARNING".to_string(),
        description: "Increase the EFFICENCY of RESEARCH DRONES by 70%".to_string(),
        cost: vec![], // vec![(Resources::Metals, 8_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Metals, 2_200)],
    },
    Upgrade {
        name: "RAPID ARCHIVING".to_string(),
        description: "Increase the SPEED of RESEARCH DRONES by 4%".to_string(),
        cost: vec![], // vec![(Resources::Power, 400)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Compounding { factor: 2.0 },
        base_cost: vec![(Resources::Power, 1_640)],
    },
    Upgrade {
        name: "RESEARCH DRONE AMP".to_string(),
        description: "Authorize construction of the DRONE AMP".to_string(),
        cost: vec![], // vec![(Resources::Research, 900)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 85_000)],
    },
    Upgrade {
        name: "RESEARCH FABRICATOR".to_string(),
        description: "Authorize construction of the FABRICATOR".to_string(),
        cost: vec![], // vec![(Resources::Research, 900)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 184_000)],
    },
    Upgrade {
        name: "RESEARCH ADV. DRONES".to_string(),
        description: "DOUBLE the EFFICENCY of ALL DRONES".to_string(),
        cost: vec![], // vec![(Resources::Research, 900)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 416_000)],
    },
    Upgrade {
        name: "RESEARCH SIMULACRUM".to_string(),
        description: "Final project to complete in this sector.".to_string(),
        cost: vec![], // vec![(Resources::Research, 900)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 4_000_000)],
    },
]);

pub static PROBE_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "EXPERTISE".to_string(),
        description: "Increase the BASE of ALL DRONES by 15".to_string(),
        cost: vec![], // vec![(Resources::Prestige, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 2,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Prestige, 1)],
    },
    Upgrade {
        name: "RESOURCEFUL".to_string(),
        description: "Retain 10% of RESOURCES when prestiging".to_string(),
        cost: vec![],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Prestige, 1)],
    },
    Upgrade {
        name: "DRONE RECALL".to_string(),
        description: "Recall any deployed DRONES from stations".to_string(),
        cost: vec![],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Prestige, 2)],
    },
    Upgrade {
        name: "INNOVATION".to_string(),
        description: "Add a BASE upgrade path to DRONE stations".to_string(),
        cost: vec![],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Prestige, 3)],
    },
    Upgrade {
        name: "RESOURCE CLONING".to_string(),
        description: "Earn 1% of collected RESOURCES every 10 seconds".to_string(),
        cost: vec![], // vec![(Resources::Prestige, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Prestige, 3)],
    },
]);

pub static AMP_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct DRONE AMP".to_string(),
        cost: vec![], // vec![(Resources::Metals, 48_000), (Resources::Power, 32_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1, 2, 3],
        u_type: UpgradeType::Purchase { btn: Btn::buy() },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Metals, 92_000), (Resources::Power, 48_000)],
    },
    Upgrade {
        name: "AMP SURVEY DRONES".to_string(),
        description: "Amplify SURVEY DRONES speed by x2".to_string(),
        cost: vec![], // vec![(Resources::Metals, 48_000), (Resources::Power, 32_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Power, 2_400)],
    },
        Upgrade {
        name: "AMP MINING DRONES".to_string(),
        description: "Amplify MINING DRONES speed by x2".to_string(),
        cost: vec![], // vec![(Resources::Metals, 48_000), (Resources::Power, 32_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Power, 2_400)],
    },
        Upgrade {
        name: "AMP CONDUIT DRONES".to_string(),
        description: "Amplify CONDUIT DRONES speed by x2".to_string(),
        cost: vec![], // vec![(Resources::Metals, 48_000), (Resources::Power, 32_000)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        u_type: UpgradeType::Toggle { toggle: Toggle::new(Bounds::new(-320, -320, 0, 0), false) },

        tooltip: WrapBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Power, 2_400)],
    },
]);