use super::*;
use once_cell::sync::Lazy;

pub static EXOPLANET_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "FIELD SCANNER".to_string(),
        description: "Increase the amount of research gathered by pressing the Exoplanet by 100%.".to_string(),
        cost: vec![(Resources::Research, 15)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 4,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Research, 15)],
    },
    Upgrade {
        name: "DEPLOY SURVEY DRONE".to_string(),
        description: "Assign a DRONE to gather RESEARCH.".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![2],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "ADV. SENSORS".to_string(),
        description: "Increase the amount of RESEARCH gathered by SURVEY DRONES by 80%.".to_string(),
        cost: vec![(Resources::Metals, 32)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 32)],
    },
    Upgrade {
        name: "BIOSCANNERS".to_string(),
        description: "Increase the speed of SURVEY DRONES by 10%.".to_string(),
        cost: vec![(Resources::Power, 40)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 40)],
    },
]);

pub static DEPOT_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct DRONE DEPOT.".to_string(),
        cost: vec![(Resources::Research, 60)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 60)],
    },
    Upgrade {
        name: "DRONE SHIPMENT".to_string(),
        description: "Exchange RESEARCH for a DRONE.".to_string(),
        cost: vec![(Resources::Research, 120)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        buy_button: Btn::buy(),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::Exponential,
        base_cost: vec![(Resources::Research, 120)],
    },
    Upgrade {
        name: "CONSTRUCT FABRICATOR".to_string(),
        description: "Construct FABRICATOR. Assign DRONES to convert METAL into DRONES.".to_string(),
        cost: vec![(Resources::Research, 3800), (Resources::Metals, 1200)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 3800), (Resources::Metals, 1200)],
    },    
    Upgrade {
        name: "DEPLOY MAKER DRONE".to_string(),
        description: "Assign a DRONE to fabricate DRONES.".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "CARGO CAPACITY".to_string(),
        description: "Increase the amount of METALS gathered by MAKER DRONES by 50%.".to_string(),
        cost: vec![(Resources::Metals, 320)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 30,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 320)],
    },
    Upgrade {
        name: "PLASMA TOOLS".to_string(),
        description: "Increase the speed of MAKER DRONES by 20%.".to_string(),
        cost: vec![(Resources::Power,240)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 30,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 240)],
    },
]);

pub static MINES_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct ASTEROID MINES.".to_string(),
        cost: vec![(Resources::Research, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1, 2],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 800)],
    },
    Upgrade {
        name: "DEPLOY MINING DRONE".to_string(),
        description: "Assign a DRONE to gather METALS.".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "DRILL AUGMENT".to_string(),
        description: "Increase the amount of METALS gathered by MINING DRONES by 100%.".to_string(),
        cost: vec![(Resources::Metals, 100)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 20,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 100)],
    },
    Upgrade {
        name: "ADV. THRUSTERS".to_string(),
        description: "Increase the speed of MINING DRONES by 5%.".to_string(),
        cost: vec![(Resources::Power, 100)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 20,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 100)],
    },
]);

pub static POWER_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct POWER PLANT.".to_string(),
        cost: vec![(Resources::Research, 6400), (Resources::Metals, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1,2,3],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 0)],
    },
    Upgrade {
        name: "DEPLOY CONDUIT DRONE".to_string(),
        description: "Assign a DRONE to gather POWER.".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
    Upgrade {
        name: "REFLECTOR CELLS".to_string(),
        description: "Increase the amount of POWER gathered by CONDUIT DRONES by 55%.".to_string(),
        cost: vec![(Resources::Metals, 100)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Metals, 100)],
    },
    Upgrade {
        name: "ARC BATTERIES".to_string(),
        description: "Increase the speed of CONDUIT DRONES by 10%.".to_string(),
        cost: vec![(Resources::Power, 320)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: true,
        cost_formula: CostFormula::Double,
        base_cost: vec![(Resources::Power, 320)],
    },
]);

pub static GATE_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct POWER PLANT.".to_string(),
        cost: vec![(Resources::Research, 6400), (Resources::Metals, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 0)],
    },
    Upgrade {
        name: "JUMP TO NEXT SECTOR".to_string(),
        description: "Prestige. Improve your drone's abilities but reset your progress.".to_string(),
        cost: vec![],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![],
    },
]);

pub static COMPLEX_UPGRADES: Lazy<Vec<Upgrade>> = Lazy::new(|| vec![
    Upgrade {
        name: "CONSTRUCT".to_string(),
        description: "Construct POWER PLANT.".to_string(),
        cost: vec![(Resources::Research, 6400), (Resources::Metals, 800)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 1,
        unlocks: vec![1],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Research, 0)],
    },
    Upgrade {
        name: "DEPLOY RESEARCH DRONE".to_string(),
        description: "Assign a DRONE to gather POWER.".to_string(),
        cost: vec![(Resources::Drones, 1)],
        entry: Btn::new("".to_string(), Bounds::new(-320, -320, 0, 0), true, 0),
        level: 0,
        max_level: 100,
        unlocks: vec![],
        buy_button: Btn::buy(),
        tooltip: TextBox::new("".to_string(), 0),
        hovered: false,
        display_lvl: false,
        cost_formula: CostFormula::None,
        base_cost: vec![(Resources::Drones, 1)],
    },
]);